### ISSUE TITLE
Add Amadly to daily emails

### ISSUE THREAD

**Issue by itirsnpk** [dhcole/daily-workflows#18]
acruz@camdenhealth.org

**Comment by dhcole** [comment]
Can you connect to the server again? Would should be able to do this there.
There's a `.profile` file in the `app` folder. Download that, open it in
notepad++, and add this to the email to line. Then reupload it. Remember,
the.profile file doesn't go into github because it has passwords.

**Comment by itirsnpk** [comment]
I assigned this to myself. Sorry. I can do it myself.

Itir
@itirsnpk

**Comment by dhcole** [comment]
Looks like this worked out. Let me know if you need anything else.
